import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

// ignore: non_constant_identifier_names
class BaseAppBar {
  static AppBar baseAppBar(context,
      {List<Widget>? action,
      IconThemeData? actionsIconTheme,
      bool automaticallyImplyLeading = true,
      Color? backgroundColor,
      PreferredSizeWidget? bottom,
      double bottomOpacity = 1.0,
      bool? centerTitle,
      Clip? clipBehavior,
      double? elevation,
      bool excludeHeaderSemantics = false,
      Widget? flexibleSpace,
      bool forceMaterialTransparency = false,
      Color? foregroundColor,
      IconThemeData? iconTheme,
      Widget? title,
      Widget? leading,
      double? leadingWidth,
      bool Function(ScrollNotification) notificationPredicate =
          defaultScrollNotificationPredicate,
      bool primary = true,
      double? scrolledUnderElevation,
      Color? shadowColor,
      ShapeBorder? shape,
      Color? surfaceTintColor,
      SystemUiOverlayStyle? systemOverlayStyle,
      double? titleSpacing,
      TextStyle? titleTextStyle,
      double? toolbarHeight,
      double toolbarOpacity = 1.0,
      TextStyle? toolbarTextStyle,
      Key? key}) {
    return AppBar(
      actions: action,
      title: title,
      actionsIconTheme: actionsIconTheme,
      automaticallyImplyLeading: automaticallyImplyLeading,
      backgroundColor: backgroundColor,
      bottom: bottom,
      bottomOpacity: bottomOpacity,
      centerTitle: centerTitle,
      clipBehavior: clipBehavior,
      elevation: elevation,
      excludeHeaderSemantics: excludeHeaderSemantics,
      flexibleSpace: flexibleSpace,
      forceMaterialTransparency: forceMaterialTransparency,
      foregroundColor: foregroundColor,
      iconTheme: iconTheme,
      leading: leading,
      leadingWidth: leadingWidth,
      notificationPredicate: notificationPredicate,
      primary: primary,
      scrolledUnderElevation: scrolledUnderElevation,
      shadowColor: shadowColor,
      shape: shape,
      surfaceTintColor: surfaceTintColor,
      systemOverlayStyle: systemOverlayStyle,
      titleSpacing: titleSpacing,
      titleTextStyle: titleTextStyle,
      toolbarHeight: toolbarHeight,
      toolbarOpacity: toolbarOpacity,
      toolbarTextStyle: toolbarTextStyle,
      key: key,
    );
  }
}
