// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkFiPtBi9HOpVovlpDUnJawwtCYJXNYIs',
    appId: '1:594109185587:web:e66f2cb2353749bd8cad46',
    messagingSenderId: '594109185587',
    projectId: 'restaurant-app-20c55',
    authDomain: 'restaurant-app-20c55.firebaseapp.com',
    storageBucket: 'restaurant-app-20c55.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAddLcuCbWhjMawtyzsguYinMNuoXlK4do',
    appId: '1:594109185587:android:79dd907fbda5ea1b8cad46',
    messagingSenderId: '594109185587',
    projectId: 'restaurant-app-20c55',
    storageBucket: 'restaurant-app-20c55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_WG5OSM8iScV4FVjwGYx0E6X_46_NQGY',
    appId: '1:594109185587:ios:a711874d5ceb0c908cad46',
    messagingSenderId: '594109185587',
    projectId: 'restaurant-app-20c55',
    storageBucket: 'restaurant-app-20c55.appspot.com',
    iosBundleId: 'com.example.restaurantAppApiDicoding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_WG5OSM8iScV4FVjwGYx0E6X_46_NQGY',
    appId: '1:594109185587:ios:a711874d5ceb0c908cad46',
    messagingSenderId: '594109185587',
    projectId: 'restaurant-app-20c55',
    storageBucket: 'restaurant-app-20c55.appspot.com',
    iosBundleId: 'com.example.restaurantAppApiDicoding',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkFiPtBi9HOpVovlpDUnJawwtCYJXNYIs',
    appId: '1:594109185587:web:af0b5a5a2f4a49d38cad46',
    messagingSenderId: '594109185587',
    projectId: 'restaurant-app-20c55',
    authDomain: 'restaurant-app-20c55.firebaseapp.com',
    storageBucket: 'restaurant-app-20c55.appspot.com',
  );
}
